name: Build XARM6 ETF LAB

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  build_ros2:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Build Docker image
      run: docker build . -t etf_container -f .docker/Dockerfile

    - name: Run Docker container
      run: docker run -d --name etf_container etf_co
      
    - name: Build xarm6-etf-lab workspace
      run: docker exec etf_container /bin/bash -c "make submodules && make dependencies && make build"