name: Build and Test
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.0.0
        with:
          path: workspace
      - name: Setting up ROS2
        uses: ichiro-its/ros2-ws-action/setup@v1.0.0
        with:
          ros2-distro: humble
      - name: Building
        run: make full_build_container