name: Build Docker Container

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to the Github Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/etflab

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./.docker/Dockerfile
          push: true
          tags: "${{ steps.meta.outputs.tags }}"

      - name: Pull the image
        run: |
          docker pull ${{ steps.meta.outputs.tags }}

      - name: Run the container with interactive bash session
        run: |
          docker run --name etf_lab_container -it --rm ${{ steps.meta.outputs.tags }} /bin/bash -c "echo 'Running command inside the container'"
