name: Build and Test
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.0.0
        with:
          path: workspace

      - shell: bash
        run: |
          sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/ros2.list

      - shell: bash
        run: |
          sudo apt update
          sudo apt install -y python3-colcon-common-extensions python3-rosdep

      - shell: bash
        run: |
          sudo rosdep init
          rosdep update
          sudo apt-get update && sudo apt-get upgrade
          sudo apt-get install --yes --reinstall ros-humble-ros-workspace \
                                           ament-cmake libangles-dev tree \
                                           ros-humble-angles ros-dev-tools \
                                           ament-lint ros-humble-ament-lint-auto
          source /opt/ros/humble/setup.sh

      - name: Building
        run: |
          cd workspace
          make submodules
          ls -la src/external_modules/gazebo_ros2_control
          ls -la src/external_modules/xarm_ros2
          cd src/etf_modules/RPMPLv2 && git checkout origin/main && cd ../../
          cd src/external_modules/gazebo_ros2_control && git checkout origin/humble && cd ../../
          cd src/external_modules/xarm_ros2 && git checkout origin/humble && cd ../../
          cd src/external_modules/xarm_ros2/xarm_sdk/cxx && git checkout origin/master && cd ../../../../
          make dependencies
          source /opt/ros/humble/setup.sh
          make build
